In [1]:
import pandas as pd
import numpy as np
import json
import os

In [2]:
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
raw = '0 - raw'
path_raw = f'./{raw}'
bronze = '1 - bronze'
path_bronze = f'./{bronze}'
silver = '2 - silver'
path_silver = f'./{silver}'
gold = '3 - gold'
path_gold = f'./{gold}'

# CAPA BRONZE

In [4]:
def create_merged_bronze_dataframe(table):
    # leer df anterior
    old_df = pd.read_parquet(f'{path_bronze}/{table}.parquet')

    # dataframe con los datos nuevos
    try:
        new_df = pd.read_parquet(f'{path_bronze}/new_data/{table}.parquet')
    except FileNotFoundError:
        print(f'No se han encontrado nuevos datos')
        return

    # concatenar ambos
    df = (
        pd.concat([old_df, new_df])
        #.sort_values(by='id')
        #.set_index('id', drop=False)
    )

    df.to_parquet(f'{path_bronze}/{table}.parquet')
    print(f'df saved in {path_bronze}/{table}.parquet')

In [ ]:
#create_merged_bronze_dataframe('pokemon')

In [9]:
#create_merged_bronze_dataframe('pokemon-species')

No se han encontrado nuevos datos

In [7]:
#create_merged_bronze_dataframe('pokemon-form')

df saved in ./1 - bronze/pokemon-form.parquet

# CAPA SILVER

# - TABLA POKEMON

In [26]:
df_raw_new = pd.read_parquet(f'{path_bronze}/new_data/pokemon.parquet')

In [71]:
df_raw_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 10278 to 10326
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   abilities                 49 non-null     object
 1   base_experience           0 non-null      object
 2   cries                     49 non-null     object
 3   forms                     49 non-null     object
 4   game_indices              49 non-null     object
 5   height                    49 non-null     int64
 6   held_items                49 non-null     object
 7   id                        49 non-null     int64
 8   is_default                49 non-null     bool
 9   location_area_encounters  49 non-null     object
 10  moves                     49 non-null     object
 11  name                      49 non-null     object
 12  order                     49 non-null     int64
 13  past_abilities            49 non-null     object
 14  past_stats                49 non-null     object
 15  past_types                49 non-null     object
 16  species                   49 non-null     object
 17  sprites                   49 non-null     object
 18  stats                     49 non-null     object
 19  types                     49 non-null     object
 20  weight                    49 non-null     int64
dtypes: bool(1), int64(4), object(16)
memory usage: 9.1+ KB

In [112]:
suffixes_mega = ('-mega','-mega-x','-mega-y','-mega-z')
suffixes_gmax = '-gmax'
suffixes_regional = ['-alola','-galar','-hisui','-paldea']

In [28]:
# etl_silver_pokemon

df_pokemon_clean = (
    df_raw_new
    .rename(columns={'name':'pokemon_name', 'order':'pokemon_order'})
)

# cries
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        cry_latest = lambda df : df['cries'].apply(lambda x : x.get('latest',None)),
        cry_legacy = lambda df : df['cries'].apply(lambda x : x.get('legacy',None))
    )
    .drop(columns=['cries'])
)

# forms
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        forms_list = lambda df : (
            df['forms'].apply(
                lambda values : [ x.get('name',None) for x in values ]
            )
        )
    )
    .drop(columns=['forms'])
)

# types
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        types_dic = lambda df : (
            df['types'].apply(
                lambda values : { 
                    x.get('slot',0) : { 'name':x.get('type',{}).get('name',None) }
                    for x in values
                }
            )
        )
    )
    .assign(
        # types
        pokemon_first_type = lambda df : df['types_dic'].apply(lambda x : x.get(1,{}).get('name',None)),
        pokemon_second_type = lambda df : df['types_dic'].apply(lambda x : x.get(2,{}).get('name',None))
    )
    .drop(columns=['types','types_dic'])
)

# stats
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        stats_dic = lambda df : (
            df['stats'].apply(
                lambda values : { 
                    x.get('stat',{}).get('name','unknown_stat') : { 'base':x.get('base_stat',0), 'effort':x.get('effort',0) }
                    for x in values 
                }
            )
        )
    )
    .assign(
        # base stats
        stat_hp_base = lambda df : df['stats_dic'].apply(lambda x : x.get('hp',{}).get('base',0)),
        stat_attack_base = lambda df : df['stats_dic'].apply(lambda x : x.get('attack',{}).get('base',0)),
        stat_defense_base = lambda df : df['stats_dic'].apply(lambda x : x.get('defense',{}).get('base',0)),
        stat_special_attack_base = lambda df : df['stats_dic'].apply(lambda x : x.get('special-attack',{}).get('base',0)),
        stat_special_defense_base = lambda df : df['stats_dic'].apply(lambda x : x.get('special-defense',{}).get('base',0)),
        stat_speed_base = lambda df : df['stats_dic'].apply(lambda x : x.get('speed',{}).get('base',0)),
        
        # effort values
        stat_hp_effort = lambda df : df['stats_dic'].apply(lambda x : x.get('hp',{}).get('effort',0)),
        stat_attack_effort = lambda df : df['stats_dic'].apply(lambda x : x.get('attack',{}).get('effort',0)),
        stat_defense_effort = lambda df : df['stats_dic'].apply(lambda x : x.get('defense',{}).get('effort',0)),
        stat_special_attack_effort = lambda df : df['stats_dic'].apply(lambda x : x.get('special-attack',{}).get('effort',0)),
        stat_special_defense_effort = lambda df : df['stats_dic'].apply(lambda x : x.get('special-defense',{}).get('effort',0)),
        stat_speed_effort = lambda df : df['stats_dic'].apply(lambda x : x.get('speed',{}).get('effort',0))
    )
    .assign(
        # total
        stats_total = lambda df : df['stat_hp_base'] + df['stat_attack_base'] + df['stat_defense_base'] + df['stat_special_attack_base'] + df['stat_special_defense_base'] + df['stat_speed_base'],
        effort_total = lambda df : df['stat_hp_effort'] + df['stat_attack_effort'] + df['stat_defense_effort'] + df['stat_special_attack_effort'] + df['stat_special_defense_effort'] + df['stat_speed_effort'] 
    )
    .drop(columns=['stats','stats_dic'])
)

# abilities
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        abilities_dic = lambda df : (
            df['abilities'].apply(
                lambda values : { 
                    x.get('slot',0) : { 'name':x.get('ability',{}).get('name',None) }
                    for x in values
                }
            )
        )
    )
    .assign(
        # abilities
        first_ability = lambda df : df['abilities_dic'].apply(lambda x : x.get(1,{}).get('name',None)),
        second_ability = lambda df : df['abilities_dic'].apply(lambda x : x.get(2,{}).get('name',None)),
        hidden_ability = lambda df : df['abilities_dic'].apply(lambda x : x.get(3,{}).get('name',None))
    )
    .drop(columns=['abilities','abilities_dic'])
)

# past abilities
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        past_first_abilities = lambda df : (
            df['past_abilities'].apply(
                lambda values :
                [ x for xs in 
                    [ 
                        [ y.get('ability',{}).get('name',None) for y in v.get('abilities',[]) if y.get('ability') and y.get('slot')==1 ]
                        for v in values 
                    ]
                 for x in xs ]
            )
        ),
        past_second_abilities = lambda df : (
            df['past_abilities'].apply(
                lambda values :
                [ x for xs in 
                    [ 
                        [ y.get('ability',{}).get('name',None) for y in v.get('abilities',[]) if y.get('ability') and y.get('slot')==2 ]
                        for v in values 
                    ]
                 for x in xs ]
            )
        ),
        past_hidden_abilities = lambda df : (
            df['past_abilities'].apply(
                lambda values :
                [ x for xs in 
                    [ 
                        [ y.get('ability',{}).get('name',None) for y in v.get('abilities',[]) if y.get('ability') and y.get('slot')==3 ]
                        for v in values 
                    ]
                 for x in xs ]
            )
        )
    )
)

# moves
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        moves_list = lambda df : (
            df['moves'].apply(
                lambda values : [ x.get('move',{}).get('name',None) for x in values ]
            )
        )
    )
)

# species name
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        species_name = lambda df : df['species'].apply(lambda x : x.get('name',None))
    )
    .drop(columns=['species'])
)

# is mega / gmax
suffixes_mega = ('-mega','-mega-x','-mega-y','-mega-z')
suffixes_gmax = '-gmax'
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        is_mega = lambda df : df['pokemon_name'].str.endswith(suffixes_mega),
        is_gmax = lambda df : df['pokemon_name'].str.endswith(suffixes_gmax)
    )
)

# is totem
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        is_totem = lambda df : df['pokemon_name'].apply(lambda values : '-totem' in values )
    )
)

# is regional form
suffixes_regional = ['-alola','-galar','-hisui','-paldea']
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        is_regional = lambda df : df['pokemon_name'].apply(lambda values : any(x in values for x in suffixes_regional) ) #if '-cap' not in values) )
    )
)

# separated from species
df_pokemon_clean['is_separated_from_species'] = False

# pokemon base name
df_pokemon_clean['pokemon_base_name'] = df_pokemon_clean['species_name']
df_pokemon_clean.loc[df_pokemon_clean.is_regional, 'pokemon_base_name'] = df_pokemon_clean.loc[df_pokemon_clean.is_regional, 'pokemon_name']

# sprite default
df_pokemon_clean = (
    df_pokemon_clean
    .assign(
        sprite_default = lambda df : df['sprites'].apply(lambda x: x.get('other',{}).get('home',{}).get('front_default',None))
    )
)

# merge con los datos anteriores

df_pokemon_old = pd.read_parquet(f'{path_silver}/pokemon.parquet')
df_pokemon_new = df_pokemon_clean

df_pokemon = (
    pd.concat([df_pokemon_old, df_pokemon_new])
)

In [ ]:
# save
#df_pokemon.to_parquet(f'{path_silver}/pokemon.parquet')

In [79]:
#df_pokemon = pd.read_parquet(f'{path_silver}/pokemon.parquet')

In [80]:
df_pokemon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1351 entries, 1 to 10326
Data columns (total 49 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   base_experience              1302 non-null   object
 1   game_indices                 1351 non-null   object
 2   height                       1351 non-null   int64
 3   held_items                   1351 non-null   object
 4   id                           1351 non-null   int64
 5   is_default                   1351 non-null   bool
 6   location_area_encounters     1351 non-null   object
 7   moves                        1351 non-null   object
 8   pokemon_name                 1351 non-null   object
 9   pokemon_order                1351 non-null   int64
 10  past_abilities               1351 non-null   object
 11  past_types                   1351 non-null   object
 12  sprites                      1351 non-null   object
 13  weight                       1316 non-null   float64
 14  cry_latest                   1351 non-null   object
 15  cry_legacy                   649 non-null    object
 16  forms_list                   1351 non-null   object
 17  pokemon_first_type           1351 non-null   object
 18  pokemon_second_type          765 non-null    object
 19  stat_hp_base                 1351 non-null   int64
 20  stat_attack_base             1351 non-null   int64
 21  stat_defense_base            1351 non-null   int64
 22  stat_special_attack_base     1351 non-null   int64
 23  stat_special_defense_base    1351 non-null   int64
 24  stat_speed_base              1351 non-null   int64
 25  stat_hp_effort               1351 non-null   int64
 26  stat_attack_effort           1351 non-null   int64
 27  stat_defense_effort          1351 non-null   int64
 28  stat_special_attack_effort   1351 non-null   int64
 29  stat_special_defense_effort  1351 non-null   int64
 30  stat_speed_effort            1351 non-null   int64
 31  stats_total                  1351 non-null   int64
 32  effort_total                 1351 non-null   int64
 33  first_ability                1337 non-null   object
 34  second_ability               613 non-null    object
 35  hidden_ability               1002 non-null   object
 36  past_first_abilities         1351 non-null   object
 37  past_second_abilities        1351 non-null   object
 38  past_hidden_abilities        1351 non-null   object
 39  moves_list                   1351 non-null   object
 40  species_name                 1351 non-null   object
 41  is_mega                      1351 non-null   bool
 42  is_gmax                      1351 non-null   bool
 43  is_totem                     1351 non-null   bool
 44  is_regional                  1351 non-null   bool
 45  is_separated_from_species    1351 non-null   bool
 46  pokemon_base_name            1351 non-null   object
 47  sprite_default               1351 non-null   object
 48  past_stats                   49 non-null     object
dtypes: bool(6), float64(1), int64(17), object(25)
memory usage: 472.3+ KB

In [81]:
df_pokemon_old.tail(1)

,base_experience,game_indices,height,held_items,id,is_default,location_area_encounters,moves,pokemon_name,pokemon_order,past_abilities,past_types,sprites,weight,cry_latest,cry_legacy,forms_list,pokemon_first_type,pokemon_second_type,stat_hp_base,stat_attack_base,stat_defense_base,stat_special_attack_base,stat_special_defense_base,stat_speed_base,stat_hp_effort,stat_attack_effort,stat_defense_effort,stat_special_attack_effort,stat_special_defense_effort,stat_speed_effort,stats_total,effort_total,first_ability,second_ability,hidden_ability,past_first_abilities,past_second_abilities,past_hidden_abilities,moves_list,species_name,is_mega,is_gmax,is_totem,is_regional,is_separated_from_species,pokemon_base_name,sprite_default
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10277,90,[],17,[],10277,False,https://pokeapi.co/api/v2/pokemon/10277/encoun...,"[{'move': {'name': 'headbutt', 'url': 'https:/...",terapagos-stellar,-1,[],[],"{'back_default': None, 'back_female': None, 'b...",770.0,https://raw.githubusercontent.com/PokeAPI/crie...,None,[terapagos-stellar],normal,None,160,105,110,130,110,85,3,0,0,0,0,0,700,3,teraform-zero,None,None,[],[],[],"[headbutt, body-slam, take-down, double-edge, ...",terapagos,False,False,False,False,False,terapagos,https://raw.githubusercontent.com/PokeAPI/spri...

In [82]:
df_pokemon_new.tail(1)

,base_experience,game_indices,height,held_items,id,is_default,location_area_encounters,moves,pokemon_name,pokemon_order,past_abilities,past_stats,past_types,sprites,weight,cry_latest,cry_legacy,forms_list,pokemon_first_type,pokemon_second_type,stat_hp_base,stat_attack_base,stat_defense_base,stat_special_attack_base,stat_special_defense_base,stat_speed_base,stat_hp_effort,stat_attack_effort,stat_defense_effort,stat_special_attack_effort,stat_special_defense_effort,stat_speed_effort,stats_total,effort_total,first_ability,second_ability,hidden_ability,past_first_abilities,past_second_abilities,past_hidden_abilities,moves_list,species_name,is_mega,is_gmax,is_totem,is_regional,is_separated_from_species,pokemon_base_name,sprite_default
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10326,None,[],8,[],10326,False,https://pokeapi.co/api/v2/pokemon/10326/encoun...,"[{'move': {'name': 'hyper-beam', 'url': 'https...",meowstic-female-mega,-1,[],[],[],{'back_default': 'https://raw.githubuserconten...,101,https://raw.githubusercontent.com/PokeAPI/crie...,None,[meowstic-female-mega],psychic,None,74,48,76,143,101,124,0,0,0,0,0,0,566,0,trace,None,None,[],[],[],"[hyper-beam, thunderbolt, thunder-wave, dig, p...",meowstic,True,False,False,False,False,meowstic,https://raw.githubusercontent.com/PokeAPI/spri...

In [18]:
df_pokemon_clean = pd.read_parquet(f'{path_silver}/backup/pokemon.parquet')

In [20]:
df_pokemon_clean.tail(1)

,base_experience,game_indices,height,held_items,id,is_default,location_area_encounters,moves,pokemon_name,pokemon_order,past_abilities,past_types,sprites,weight,cry_latest,cry_legacy,forms_list,pokemon_first_type,pokemon_second_type,stat_hp_base,stat_attack_base,stat_defense_base,stat_special_attack_base,stat_special_defense_base,stat_speed_base,stat_hp_effort,stat_attack_effort,stat_defense_effort,stat_special_attack_effort,stat_special_defense_effort,stat_speed_effort,stats_total,effort_total,first_ability,second_ability,hidden_ability,past_first_abilities,past_second_abilities,past_hidden_abilities,moves_list,species_name,is_mega,is_gmax,is_totem,is_regional,is_separated_from_species,pokemon_base_name,sprite_default
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10277,90,[],17,[],10277,False,https://pokeapi.co/api/v2/pokemon/10277/encoun...,"[{'move': {'name': 'headbutt', 'url': 'https:/...",terapagos-stellar,-1,[],[],"{'back_default': None, 'back_female': None, 'b...",770.0,https://raw.githubusercontent.com/PokeAPI/crie...,None,[terapagos-stellar],normal,None,160,105,110,130,110,85,3,0,0,0,0,0,700,3,teraform-zero,None,None,[],[],[],"[headbutt, body-slam, take-down, double-edge, ...",terapagos,False,False,False,False,False,terapagos,https://raw.githubusercontent.com/PokeAPI/spri...

# - TABLA POKEMON-SPECIES

In [ ]:
#df_species_raw_new = pd.read_parquet(f'{path_bronze}/new_data/pokemon-species.parquet')

In [87]:
df_species_raw_old = pd.read_parquet(f'{path_bronze}/pokemon-species.parquet')

In [88]:
df_species_raw_old.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1025 entries, 1 to 1025
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   base_happiness          1025 non-null   int64
 1   capture_rate            1025 non-null   int64
 2   color                   1025 non-null   object
 3   egg_groups              1025 non-null   object
 4   evolution_chain         1025 non-null   object
 5   evolves_from_species    484 non-null    object
 6   flavor_text_entries     1025 non-null   object
 7   form_descriptions       1025 non-null   object
 8   forms_switchable        1025 non-null   bool
 9   gender_rate             1025 non-null   int64
 10  genera                  1025 non-null   object
 11  generation              1025 non-null   object
 12  growth_rate             1025 non-null   object
 13  habitat                 386 non-null    object
 14  has_gender_differences  1025 non-null   bool
 15  hatch_counter           1025 non-null   int64
 16  id                      1025 non-null   int64
 17  is_baby                 1025 non-null   bool
 18  is_legendary            1025 non-null   bool
 19  is_mythical             1025 non-null   bool
 20  name                    1025 non-null   object
 21  names                   1025 non-null   object
 22  order                   1025 non-null   int64
 23  pal_park_encounters     1025 non-null   object
 24  pokedex_numbers         1025 non-null   object
 25  shape                   1025 non-null   object
 26  varieties               1025 non-null   object
dtypes: bool(5), int64(6), object(16)
memory usage: 189.2+ KB

In [110]:
df_species_raw_new = df_species_raw_old

In [119]:
# etl_silver_pokemon_species

df_species_clean = (
    df_species_raw_new
    .assign(
        # normalize
        color_name = lambda df : df['color'].apply(lambda x : x.get('name',None) if x is not None else x),
        species_generation_name = lambda df : df['generation'].apply(lambda x : x.get('name',None) if x is not None else x),
        growth_rate_name = lambda df : df['growth_rate'].apply(lambda x : x.get('name',None) if x is not None else x),
        habitat_name = lambda df : df['habitat'].apply(lambda x : x.get('name',None) if x is not None else x),
        shape_name = lambda df : df['shape'].apply(lambda x : x.get('name',None) if x is not None else x),
        evolves_from_species_name = lambda df : df['evolves_from_species'].apply(lambda x : x.get('name',None) if x is not None else x),
        is_sublegendary = False,
        is_powerhouse = False
    )
    .drop(columns=['color','generation','growth_rate','habitat','shape','evolves_from_species'])
    .rename(columns={'id':'species_id', 'name':'species_name', 'names':'species_names', 'order':'species_order'})
)

# egg_groups
df_species_clean = (
    df_species_clean
    .assign(
        egg_groups_dic = lambda df : (
            df['egg_groups'].apply(
                lambda values : { 
                    n : x.get('name', None)
                    for n,x in enumerate(values, start=1)
                }
            )
        )
    )
    .assign(
        # egg_groups
        first_egg_group = lambda df : df['egg_groups_dic'].apply(lambda x : x.get(1,None)),
        second_egg_group = lambda df : df['egg_groups_dic'].apply(lambda x : x.get(2,None))
    )
    .drop(columns=['egg_groups','egg_groups_dic'])
)

# generation
generations_dic = {
    'generation-i' : 1,
    'generation-ii' : 2,
    'generation-iii' : 3,
    'generation-iv' : 4,
    'generation-v' : 5,
    'generation-vi' : 6,
    'generation-vii' : 7,
    'generation-viii' : 8,
    'generation-ix' : 9
}
df_species_clean = (
    df_species_clean
    .assign(
        species_generation_number = lambda df : df['species_generation_name'].map(generations_dic)
    )
    .drop(columns=['species_generation_name'])
)

# varieties
df_species_clean = (
    df_species_clean
    .assign(
        varieties_list = lambda df : (
            df['varieties'].apply(
                lambda values : [
                    x.get('pokemon',{}).get('name', None)
                    for x in values
                ]
            )
        )
    )
    .drop(columns=['varieties'])
)


'''
# añadir nuevos varieties dentro de la lista de cada especie
new_data_pokemon_df = pd.read_parquet(f'{path_raw}/new_data/pokemon.parquet')
new_pokemon_ids = new_data_pokemon_df.id.tolist()
for i in new_pokemon_ids:
    row = df_pokemon.loc[i]
    poke = row['pokemon_name']
    species = row['species_name']
    varieties = df_species_clean[df_species_clean.species_name==species].varieties_list
    for v_list in varieties:
        if poke not in v_list:
            v_list.append(poke)
'''

# has mega / gmax
df_species_clean = (
    df_species_clean
    .assign(
        has_mega = lambda df : df['varieties_list'].apply( lambda values : any(x.endswith(suffixes_mega) for x in values) ),
        has_gmax = lambda df : df['varieties_list'].apply( lambda values : any(x.endswith(suffixes_gmax) for x in values) )
    )
)

# has regional form
df_species_clean = (
    df_species_clean
    .assign(
        has_regional = lambda df : df['varieties_list'].apply( lambda values : any(suffix in x for suffix in suffixes_regional for x in values) ),
    )
)

# evolution_chain_url to id
df_species_clean = (
    df_species_clean
    .assign(
        evolution_chain_id = lambda df : (
            df['evolution_chain']
            .apply(lambda x : x.get('url',None) if x is not None else x)
            .str.replace('https://pokeapi.co/api/v2/evolution-chain','')
            .str.replace('/','')
        )
        .astype(int)
    )
    .drop(columns=['evolution_chain'])
)

# form_description
df_species_clean = (
    df_species_clean
    .assign(
        forms_description = lambda df : df['form_descriptions'].apply(lambda x : x[0].get('description',None) if len(x)>0 else None)
    )
    .drop(columns=['form_descriptions'])
)

# genus
df_species_clean = (
    df_species_clean
    .assign(
        genera_dic = lambda df : df['genera'].apply(
            lambda values : { 
                x.get('language',{}).get('name','default') : x.get('genus',None)
                for x in values
            }
        )
    )
    .assign(
        genus = lambda df : df['genera_dic'].apply(lambda x : x.get('en',None))
    )
    .drop(columns=['genera','genera_dic'])
)

# species_names
species_names_df =(
    pd.json_normalize(
        df_species_clean['species_names'].apply(
            lambda values : { 
                'species_name_'+(x.get('language',{}).get('name','default')).replace('-','_') : x.get('name',None)
                for x in values
            }
        )
    )
)
species_names_df.index = df_species_clean.index

df_species_clean = (
    df_species_clean
    .merge(species_names_df, left_index=True, right_index=True, how='left')
    .drop(columns=['species_names'])
)

# flavor_text_entries
flavor_text_entries_df =(
    pd.json_normalize(
        df_species_clean['flavor_text_entries'].apply(
            lambda values : { 
                (x.get('version',{}).get('name','v') +'_'+ x.get('language',{}).get('name','lang')).replace('-','_') : x.get('flavor_text',None)
                for x in values
            }
        )
    )
)
flavor_text_entries_df.index = df_species_clean.index

game_entries_columns=[
    'red_en', 'blue_en', 'yellow_en', 
    'gold_en', 'silver_en', 'crystal_en',
    'ruby_en', 'sapphire_en', 'emerald_en', 'firered_en', 'leafgreen_en',
    'diamond_en', 'pearl_en', 'platinum_en', 'heartgold_en', 'soulsilver_en', 
    'black_en', 'white_en', 'black_2_en', 'white_2_en',
    'x_en', 'y_en', 'omega_ruby_en', 'alpha_sapphire_en', 
    'sun_en', 'moon_en', 'ultra_sun_en', 'ultra_moon_en', 'lets_go_pikachu_en', 'lets_go_eevee_en', 
    'sword_en', 'shield_en', 'legends_arceus_en', 
    'scarlet_en', 'violet_en'
]

df_species_clean = (
    df_species_clean
    .merge(flavor_text_entries_df[game_entries_columns], left_index=True, right_index=True, how='left')
    .drop(columns=['flavor_text_entries'])
)

In [121]:
# save
df_species.to_parquet(f'./{silver}/pokemon-species.parquet')

In [14]:
df_species_clean = pd.read_parquet(f'./{silver}/backup/pokemon-species.parquet')

In [15]:
df_species_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1025 entries, 1 to 1025
Data columns (total 77 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   base_happiness             1025 non-null   int64
 1   capture_rate               1025 non-null   int64
 2   forms_switchable           1025 non-null   bool
 3   gender_rate                1025 non-null   int64
 4   has_gender_differences     1025 non-null   bool
 5   hatch_counter              1025 non-null   int64
 6   species_id                 1025 non-null   int64
 7   is_baby                    1025 non-null   bool
 8   is_legendary               1025 non-null   bool
 9   is_mythical                1025 non-null   bool
 10  species_name               1025 non-null   object
 11  species_order              1025 non-null   int64
 12  pal_park_encounters        1025 non-null   object
 13  pokedex_numbers            1025 non-null   object
 14  color_name                 1025 non-null   object
 15  growth_rate_name           1025 non-null   object
 16  habitat_name               386 non-null    object
 17  shape_name                 1025 non-null   object
 18  evolves_from_species_name  484 non-null    object
 19  is_sublegendary            1025 non-null   bool
 20  is_powerhouse              1025 non-null   bool
 21  first_egg_group            1025 non-null   object
 22  second_egg_group           279 non-null    object
 23  species_generation_number  1025 non-null   int64
 24  varieties_list             1025 non-null   object
 25  has_mega                   1025 non-null   bool
 26  has_gmax                   1025 non-null   bool
 27  has_regional               1025 non-null   bool
 28  evolution_chain_id         1025 non-null   int64
 29  forms_description          42 non-null     object
 30  genus                      1025 non-null   object
 31  species_name_ja_Hrkt       1025 non-null   object
 32  species_name_roomaji       1010 non-null   object
 33  species_name_ko            1025 non-null   object
 34  species_name_zh_Hant       1025 non-null   object
 35  species_name_fr            1025 non-null   object
 36  species_name_de            1025 non-null   object
 37  species_name_es            1025 non-null   object
 38  species_name_it            1025 non-null   object
 39  species_name_en            1025 non-null   object
 40  species_name_ja            1025 non-null   object
 41  species_name_zh_Hans       1025 non-null   object
 42  red_en                     151 non-null    object
 43  blue_en                    151 non-null    object
 44  yellow_en                  151 non-null    object
 45  gold_en                    251 non-null    object
 46  silver_en                  251 non-null    object
 47  crystal_en                 251 non-null    object
 48  ruby_en                    386 non-null    object
 49  sapphire_en                386 non-null    object
 50  emerald_en                 386 non-null    object
 51  firered_en                 386 non-null    object
 52  leafgreen_en               386 non-null    object
 53  diamond_en                 493 non-null    object
 54  pearl_en                   493 non-null    object
 55  platinum_en                493 non-null    object
 56  heartgold_en               493 non-null    object
 57  soulsilver_en              493 non-null    object
 58  black_en                   649 non-null    object
 59  white_en                   649 non-null    object
 60  black_2_en                 649 non-null    object
 61  white_2_en                 649 non-null    object
 62  x_en                       721 non-null    object
 63  y_en                       721 non-null    object
 64  omega_ruby_en              721 non-null    object
 65  alpha_sapphire_en          721 non-null    object
 66  sun_en                     302 non-null    object
 67  moon_en                    302 non-null    object
 68  ultra_sun_en               403 non-null    object
 69  ultra_moon_en              403 non-null    object
 70  lets_go_pikachu_en         153 non-null    object
 71  lets_go_eevee_en           153 non-null    object
 72  sword_en                   609 non-null    object
 73  shield_en                  609 non-null    object
 74  legends_arceus_en          241 non-null    object
 75  scarlet_en                 120 non-null    object
 76  violet_en                  120 non-null    object
dtypes: bool(10), int64(8), object(59)
memory usage: 554.5+ KB

In [16]:
df_species_clean.tail(1)

,base_happiness,capture_rate,forms_switchable,gender_rate,has_gender_differences,hatch_counter,species_id,is_baby,is_legendary,is_mythical,species_name,species_order,pal_park_encounters,pokedex_numbers,color_name,growth_rate_name,habitat_name,shape_name,evolves_from_species_name,is_sublegendary,is_powerhouse,first_egg_group,second_egg_group,species_generation_number,varieties_list,has_mega,has_gmax,has_regional,evolution_chain_id,forms_description,genus,species_name_ja_Hrkt,species_name_roomaji,species_name_ko,species_name_zh_Hant,species_name_fr,species_name_de,species_name_es,species_name_it,species_name_en,species_name_ja,species_name_zh_Hans,red_en,blue_en,yellow_en,gold_en,silver_en,crystal_en,ruby_en,sapphire_en,emerald_en,firered_en,leafgreen_en,diamond_en,pearl_en,platinum_en,heartgold_en,soulsilver_en,black_en,white_en,black_2_en,white_2_en,x_en,y_en,omega_ruby_en,alpha_sapphire_en,sun_en,moon_en,ultra_sun_en,ultra_moon_en,lets_go_pikachu_en,lets_go_eevee_en,sword_en,shield_en,legends_arceus_en,scarlet_en,violet_en
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1025,0,3,False,-1,False,20,1025,False,False,True,pecharunt,1027,[],"[{'entry_number': 1025, 'pokedex': {'name': 'n...",purple,slow,None,ball,None,False,False,no-eggs,None,9,[pecharunt],False,False,False,549,None,Subjugation Pokémon,モモワロウ,None,복숭악동,桃歹郎,Pêchaminus,Infamomo,Pecharunt,Pecharunt,Pecharunt,モモワロウ,桃歹郎,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,It feeds others toxic mochi that draw out desi...,Its peach-shaped shell serves as storage for a...

# - TABLA POKEMON-FORM

In [96]:
df_forms_raw_new = pd.read_parquet(f'{path_bronze}/new_data/pokemon-form.parquet')

In [97]:
df_forms_raw_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 10503 to 10554
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   form_name           52 non-null     object
 1   form_names          52 non-null     object
 2   form_order          52 non-null     int64
 3   id                  52 non-null     int64
 4   is_battle_only      52 non-null     bool
 5   is_default          52 non-null     bool
 6   is_mega             52 non-null     bool
 7   name                52 non-null     object
 8   names               52 non-null     object
 9   order               52 non-null     int64
 10  pokemon             52 non-null     object
 11  sprites             52 non-null     object
 12  trigger_conditions  52 non-null     object
 13  types               52 non-null     object
 14  version_group       52 non-null     object
dtypes: bool(3), int64(3), object(9)
memory usage: 5.4+ KB

In [99]:
# etl_silver_pokemon_forms

df_form_clean = (
    df_forms_raw_new
    .assign(
        pokemon_name = lambda df : df['pokemon'].apply(lambda x : x.get('name',None) if x is not None else x),
        version_group_name = lambda df : df['version_group'].apply(lambda x : x.get('name',None) if x is not None else x)
    )
    .drop(columns=['pokemon', 'version_group', 'is_default', 'is_mega'])
    .rename(columns={
        'id':'form_id', 
        'name':'pokemon_form_name', 
        'names':'pokemon_form_names', 
        'order':'form_order_global', 
        'form_order':'form_order_species'}
    )
)

# types
df_form_clean = (
    df_form_clean
    .assign(
        types_dic = lambda df : (
            df['types'].apply(
                lambda values : { 
                    x.get('slot',0) : { 'name':x.get('type',{}).get('name',None) }
                    for x in values
                }
            )
        )
    )
    .assign(
        # types
        first_type = lambda df : df['types_dic'].apply(lambda x : x.get(1,{}).get('name',None)),
        second_type = lambda df : df['types_dic'].apply(lambda x : x.get(2,{}).get('name',None))
    )
    .drop(columns=['types','types_dic'])
)

# generation
version_generation = {
    'red-blue': 1,
    'red-green-japan': 1,
    'blue-japan': 1,
    'yellow': 1,
    'gold-silver': 2,
    'crystal': 2,
    'ruby-sapphire': 3,
    'emerald': 3,
    'firered-leafgreen': 3,
    'colosseum': 3,
    'xd': 3,
    'diamond-pearl': 4,
    'platinum': 4,
    'heartgold-soulsilver': 4,
    'black-white': 5,
    'black-2-white-2': 5,
    'x-y': 6,
    'omega-ruby-alpha-sapphire': 6,
    'sun-moon': 7,
    'ultra-sun-ultra-moon': 7,
    'lets-go-pikachu-lets-go-eevee': 7,
    'sword-shield': 8,
    'the-isle-of-armor': 8,
    'the-crown-tundra': 8,
    'brilliant-diamond-and-shining-pearl': 8,
    'legends-arceus': 8,
    'scarlet-violet': 9,
    'the-teal-mask': 9,
    'the-indigo-disk': 9,
    'legends-z-a': 9,
    'mega-dimension': 9,
}

df_form_clean = (
    df_form_clean
    .assign(
        # generation
        form_generation_number = lambda df : df['version_group_name'].map(version_generation).astype(int)
    )
)

# version names
version_names = {
    'red-blue': 'red-and-blue',
    'red-green-japan': 'red-and-green-japan',
    'gold-silver': 'gold-and-silver',
    'ruby-sapphire': 'ruby-and-sapphire',
    'firered-leafgreen': 'firered-and-leafgreen',
    'diamond-pearl': 'diamond-and-pearl',
    'heartgold-soulsilver': 'heartgold-and-soulsilver',
    'black-white': 'black-and-white',
    'black-2-white-2': 'black-2-and-white-2',
    'x-y': 'x-and-y',
    'omega-ruby-alpha-sapphire': 'omega-ruby-and-alpha-sapphire',
    'sun-moon': 'sun-and-moon',
    'ultra-sun-ultra-moon': 'ultra-sun-and-ultra-moon',
    'lets-go-pikachu-lets-go-eevee': 'lets-go-pikachu-and-lets-go-eevee',
    'sword-shield': 'sword-and-shield',
    'scarlet-violet': 'scarlet-and-violet',
}

df_form_clean = (
    df_form_clean
    .assign(
        # versions
        version_group_name = lambda df : df['version_group_name'].map(lambda x: version_names.get(x, x) )
    )
)

# sprite
df_form_clean = (
    df_form_clean
    .assign(
        sprite_form = lambda df : df['sprites'].apply(lambda x : x.get('front_default',None))
    )
    .drop(columns=['sprites'])
)

# form name
df_form_clean.form_name = df_form_clean.form_name.replace(r'^$', None, regex=True)

df_form_clean = (
    df_form_clean
    .assign(
        form_names_dic = lambda df : df['form_names'].apply(
            lambda values : { 
                x.get('language',{}).get('name','lang').replace('-','_') : x.get('name',None)
                for x in values
            }
        )
    )
    .assign(
        form_name_text = lambda df : df['form_names_dic'].apply(lambda x : x.get('en',None))
    )
    .drop(columns=['form_names','form_names_dic'])
)

# pokemon_form_names
df_form_clean = (
    df_form_clean
    .assign(
        pokemon_form_names_dic = lambda df : df['pokemon_form_names'].apply(
            lambda values : { 
                x.get('language',{}).get('name','lang').replace('-','_') : x.get('name',None)
                for x in values
            }
        )
    )
    .assign(
        pokemon_form_name_text = lambda df : df['pokemon_form_names_dic'].apply(lambda x : x.get('en',None))
    )
    .drop(columns=['pokemon_form_names','pokemon_form_names_dic'])
)

In [104]:
# save
df_forms.to_parquet(f'./{silver}/pokemon-form.parquet')

In [28]:
df_form_clean = pd.read_parquet(f'./{silver}/backup/pokemon-form.parquet')

In [29]:
df_form_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1459 entries, 1 to 10475
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   form_name               494 non-null    object
 1   form_order_species      1459 non-null   int64
 2   form_id                 1459 non-null   int64
 3   is_battle_only          1459 non-null   bool
 4   pokemon_form_name       1459 non-null   object
 5   form_order_global       1459 non-null   int64
 6   pokemon_name            1459 non-null   object
 7   version_group_name      1459 non-null   object
 8   first_type              1459 non-null   object
 9   second_type             758 non-null    object
 10  form_generation_number  1459 non-null   int64
 11  sprite_form             1423 non-null   object
 12  form_name_text          497 non-null    object
 13  pokemon_form_name_text  467 non-null    object
dtypes: bool(1), int64(4), object(9)
memory usage: 161.0+ KB

In [30]:
df_form_clean.tail(1)

,form_name,form_order_species,form_id,is_battle_only,pokemon_form_name,form_order_global,pokemon_name,version_group_name,first_type,second_type,form_generation_number,sprite_form,form_name_text,pokemon_form_name_text
id,,,,,,,,,,,,,,
10475,rainbow-swirl-star-sweet,36,10475,False,alcremie-rainbow-swirl-star-sweet,1222,alcremie,sword-and-shield,fairy,None,8,https://raw.githubusercontent.com/PokeAPI/spri...,Rainbow Swirl Star Sweet,Rainbow Swirl Star Sweet Alcremie

---

# - Merge de tablas

df_pokemon_clean = pd.read_parquet(f'./{silver}/pokemon.parquet')
df_species_clean = pd.read_parquet(f'./{silver}/pokemon-species.parquet')
df_form_clean = pd.read_parquet(f'./{silver}/pokemon-form.parquet')

In [126]:
species_columns = [
    'species_name', 
    'has_gender_differences', 
    'is_mythical', 'is_legendary', 'is_sublegendary', 'is_powerhouse', #'is_baby',
    'evolves_from_species_name', 
    'has_mega', 'has_gmax', #'has_regional',
    'species_id', 'species_name_en' #, 'genus'
]

In [127]:
df_merge = (
    df_pokemon_clean
    .merge(
        df_species_clean
        .loc[:, species_columns]
        .rename(columns={'evolves_from_species_name':'evolves_from_pokemon_base_name'}),
        on='species_name', how='left'
    )
    .sort_values(by='id')
    .set_index('id', drop=False)
)


# evolves_from_pokemon_base_name
df_merge.loc[(df_merge.is_separated_from_species | df_merge.is_mega | df_merge.is_gmax), 'evolves_from_pokemon_base_name'] = None

In [128]:
# arreglos primer conjunto

## ---------------

In [129]:
# evolutions
df_merge['evolutions'] = [[] for x in range(len(df_merge))]

for index, row in df_merge.iterrows():

    preevo = row['evolves_from_pokemon_base_name']
    
    if preevo is not None:
        poke = row['pokemon_base_name']

        for i, r in df_merge[df_merge['pokemon_base_name']==preevo].iterrows():
            # añadir evolution
            if (
                not r.is_separated_from_species and 
                not r.is_mega and
                not r.is_gmax and
                poke not in r['evolutions'] 
            ):
                r['evolutions'].append(poke)

In [130]:
# arreglar merge
df_merge.loc[ df_merge.is_mega, ['has_mega','has_gmax'] ] = False
df_merge.loc[ df_merge.is_gmax, ['has_mega','has_gmax'] ] = False

df_merge.loc[~df_merge.is_default & df_merge.has_mega, 'has_mega'] = False
df_merge.loc[~df_merge.is_default & df_merge.has_gmax, 'has_gmax'] = False

#df_merge.loc[ ~df_merge.is_default, 'has_regional' ] = False

df_merge.loc[ df_merge.is_mega, 'has_gender_differences' ] = False
df_merge.loc[ df_merge.is_gmax, 'has_gender_differences' ] = False

df_merge.loc[ df_merge.is_powerhouse & (df_merge.is_totem | df_merge.is_mega | df_merge.is_gmax) , 'is_powerhouse' ] = False

In [40]:
# save
df_merge.to_parquet(f'./{silver}/pokemon.parquet')

In [4]:
df_merge = pd.read_parquet(f'./{silver}/pokemon.parquet')

In [120]:
#df_merge = df_merge.drop(['is_baby','has_regional','genus'], axis=1)

In [131]:
df_merge.info(max_cols=300)

<class 'pandas.core.frame.DataFrame'>
Index: 1302 entries, 1 to 10277
Data columns (total 59 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   base_experience                 1302 non-null   int64
 1   game_indices                    1302 non-null   object
 2   height                          1302 non-null   int64
 3   held_items                      1302 non-null   object
 4   id                              1302 non-null   int64
 5   is_default                      1302 non-null   bool
 6   location_area_encounters        1302 non-null   object
 7   moves                           1302 non-null   object
 8   pokemon_name                    1302 non-null   object
 9   pokemon_order                   1302 non-null   int64
 10  past_abilities                  1302 non-null   object
 11  past_types                      1302 non-null   object
 12  sprites                         1302 non-null   object
 13  weight                          1267 non-null   float64
 14  cry_latest                      1302 non-null   object
 15  cry_legacy                      649 non-null    object
 16  forms_list                      1302 non-null   object
 17  pokemon_first_type              1302 non-null   object
 18  pokemon_second_type             726 non-null    object
 19  stat_hp_base                    1302 non-null   int64
 20  stat_attack_base                1302 non-null   int64
 21  stat_defense_base               1302 non-null   int64
 22  stat_special_attack_base        1302 non-null   int64
 23  stat_special_defense_base       1302 non-null   int64
 24  stat_speed_base                 1302 non-null   int64
 25  stat_hp_effort                  1302 non-null   int64
 26  stat_attack_effort              1302 non-null   int64
 27  stat_defense_effort             1302 non-null   int64
 28  stat_special_attack_effort      1302 non-null   int64
 29  stat_special_defense_effort     1302 non-null   int64
 30  stat_speed_effort               1302 non-null   int64
 31  stats_total                     1302 non-null   int64
 32  effort_total                    1302 non-null   int64
 33  first_ability                   1302 non-null   object
 34  second_ability                  613 non-null    object
 35  hidden_ability                  1002 non-null   object
 36  past_first_abilities            1302 non-null   object
 37  past_second_abilities           1302 non-null   object
 38  past_hidden_abilities           1302 non-null   object
 39  moves_list                      1302 non-null   object
 40  species_name                    1302 non-null   object
 41  is_mega                         1302 non-null   bool
 42  is_gmax                         1302 non-null   bool
 43  is_totem                        1302 non-null   bool
 44  is_regional                     1302 non-null   bool
 45  is_separated_from_species       1302 non-null   bool
 46  pokemon_base_name               1302 non-null   object
 47  sprite_default                  1302 non-null   object
 48  has_gender_differences          1302 non-null   bool
 49  is_mythical                     1302 non-null   bool
 50  is_legendary                    1302 non-null   bool
 51  is_sublegendary                 1302 non-null   bool
 52  is_powerhouse                   1302 non-null   bool
 53  evolves_from_pokemon_base_name  531 non-null    object
 54  has_mega                        1302 non-null   bool
 55  has_gmax                        1302 non-null   bool
 56  species_id                      1302 non-null   int64
 57  species_name_en                 1302 non-null   object
 58  evolutions                      1302 non-null   object
dtypes: bool(13), float64(1), int64(19), object(26)
memory usage: 526.9+ KB

In [54]:
df_merge.head(1)

,base_experience,game_indices,height,held_items,id,is_default,location_area_encounters,moves,pokemon_name,pokemon_order,past_abilities,past_types,sprites,weight,cry_latest,cry_legacy,forms_list,pokemon_first_type,pokemon_second_type,stat_hp_base,stat_attack_base,stat_defense_base,stat_special_attack_base,stat_special_defense_base,stat_speed_base,stat_hp_effort,stat_attack_effort,stat_defense_effort,stat_special_attack_effort,stat_special_defense_effort,stat_speed_effort,stats_total,effort_total,first_ability,second_ability,hidden_ability,past_first_abilities,past_second_abilities,past_hidden_abilities,moves_list,species_name,is_mega,is_gmax,is_totem,is_regional,is_separated_from_species,pokemon_base_name,sprite_default,has_gender_differences,is_mythical,is_legendary,is_sublegendary,is_powerhouse,evolves_from_pokemon_base_name,has_mega,has_gmax,species_id,species_name_en,evolutions
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,64,"[{'game_index': 153, 'version': {'name': 'red'...",7,[],1,True,https://pokeapi.co/api/v2/pokemon/1/encounters,"[{'move': {'name': 'razor-wind', 'url': 'https...",bulbasaur,1,"[{'abilities': [{'ability': None, 'is_hidden':...",[],{'back_default': 'https://raw.githubuserconten...,69.0,https://raw.githubusercontent.com/PokeAPI/crie...,https://raw.githubusercontent.com/PokeAPI/crie...,[bulbasaur],grass,poison,45,49,49,65,65,45,0,0,0,1,0,0,318,1,overgrow,None,chlorophyll,[],[],[],"[razor-wind, swords-dance, cut, bind, vine-whi...",bulbasaur,False,False,False,False,False,bulbasaur,https://raw.githubusercontent.com/PokeAPI/spri...,False,False,False,False,False,None,False,False,1,Bulbasaur,[ivysaur]

In [41]:
df_full = (
    df_form_clean
    .merge(
        df_merge, 
        on='pokemon_name', how='left'
    )
    .sort_values(by='form_id')
    .set_index('form_id', drop=False)
)

# sprites
lista_formas = df_merge[df_merge.forms_list.apply(len)>1].forms_list.apply(lambda values: values[1:]).explode().to_list()
lista_indices = [ df_full.loc[df_full[df_full.pokemon_form_name==x].index].index for x in lista_formas ]
lista_ids = [ int(x[0]) for x in lista_indices if len(x)>0 ]
for x in lista_ids:
    df_full.at[x, 'sprite_default'] = df_full.at[x, 'sprite_form']

# is_default
df_full.loc[0:9999, 'is_default'] = True
df_full.loc[10000:, 'is_default'] = False

In [45]:
df_full.iloc[[0,-1]]

,form_name,form_order_species,form_id,is_battle_only,pokemon_form_name,form_order_global,pokemon_name,version_group_name,first_type,second_type,form_generation_number,sprite_form,form_name_text,pokemon_form_name_text,base_experience,game_indices,height,held_items,id,is_default,location_area_encounters,moves,pokemon_order,past_abilities,past_types,sprites,weight,cry_latest,cry_legacy,forms_list,pokemon_first_type,pokemon_second_type,stat_hp_base,stat_attack_base,stat_defense_base,stat_special_attack_base,stat_special_defense_base,stat_speed_base,stat_hp_effort,stat_attack_effort,stat_defense_effort,stat_special_attack_effort,stat_special_defense_effort,stat_speed_effort,stats_total,effort_total,first_ability,second_ability,hidden_ability,past_first_abilities,past_second_abilities,past_hidden_abilities,moves_list,species_name,is_mega,is_gmax,is_totem,is_regional,is_separated_from_species,pokemon_base_name,sprite_default,has_gender_differences,is_mythical,is_legendary,is_sublegendary,is_powerhouse,evolves_from_pokemon_base_name,has_mega,has_gmax,species_id,species_name_en,evolutions
form_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,None,1,1,False,bulbasaur,1,bulbasaur,red-and-blue,grass,poison,1,https://raw.githubusercontent.com/PokeAPI/spri...,None,None,64,"[{'game_index': 153, 'version': {'name': 'red'...",7,[],1,True,https://pokeapi.co/api/v2/pokemon/1/encounters,"[{'move': {'name': 'razor-wind', 'url': 'https...",1,"[{'abilities': [{'ability': None, 'is_hidden':...",[],{'back_default': 'https://raw.githubuserconten...,69.0,https://raw.githubusercontent.com/PokeAPI/crie...,https://raw.githubusercontent.com/PokeAPI/crie...,[bulbasaur],grass,poison,45,49,49,65,65,45,0,0,0,1,0,0,318,1,overgrow,None,chlorophyll,[],[],[],"[razor-wind, swords-dance, cut, bind, vine-whi...",bulbasaur,False,False,False,False,False,bulbasaur,https://raw.githubusercontent.com/PokeAPI/spri...,False,False,False,False,False,None,False,False,1,Bulbasaur,[ivysaur]
10475,rainbow-swirl-star-sweet,36,10475,False,alcremie-rainbow-swirl-star-sweet,1222,alcremie,sword-and-shield,fairy,None,8,https://raw.githubusercontent.com/PokeAPI/spri...,Rainbow Swirl Star Sweet,Rainbow Swirl Star Sweet Alcremie,173,[],3,[],869,False,https://pokeapi.co/api/v2/pokemon/869/encounters,"[{'move': {'name': 'tackle', 'url': 'https://p...",1053,[],[],{'back_default': 'https://raw.githubuserconten...,5.0,https://raw.githubusercontent.com/PokeAPI/crie...,None,"[alcremie-vanilla-cream-strawberry-sweet, alcr...",fairy,None,65,60,75,110,121,64,0,0,0,0,2,0,495,2,sweet-veil,None,aroma-veil,[],[],[],"[tackle, hyper-beam, solar-beam, psychic, reco...",alcremie,False,False,False,False,False,alcremie,https://raw.githubusercontent.com/PokeAPI/spri...,False,False,False,False,False,milcery,False,True,869,Alcremie,[]

In [46]:
# save
df_full.to_parquet(f'./{silver}/merged_full.parquet')

In [5]:
df_full = pd.read_parquet(f'./{silver}/merged_full.parquet')

In [19]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1459 entries, 1 to 10475
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   form_id                         1459 non-null   int64
 1   species_name_en                 1459 non-null   object
 2   form_name_text                  497 non-null    object
 3   form_generation_number          1459 non-null   int64
 4   evolves_from_pokemon_base_name  617 non-null    object
 5   evolutions                      1459 non-null   object
 6   first_type                      1459 non-null   object
 7   second_type                     758 non-null    object
 8   stat_hp_base                    1459 non-null   int64
 9   stat_attack_base                1459 non-null   int64
 10  stat_defense_base               1459 non-null   int64
 11  stat_special_attack_base        1459 non-null   int64
 12  stat_special_defense_base       1459 non-null   int64
 13  stat_speed_base                 1459 non-null   int64
 14  stat_hp_effort                  1459 non-null   int64
 15  stat_attack_effort              1459 non-null   int64
 16  stat_defense_effort             1459 non-null   int64
 17  stat_special_attack_effort      1459 non-null   int64
 18  stat_special_defense_effort     1459 non-null   int64
 19  stat_speed_effort               1459 non-null   int64
 20  stats_total                     1459 non-null   int64
 21  effort_total                    1459 non-null   int64
 22  first_ability                   1459 non-null   object
 23  second_ability                  640 non-null    object
 24  hidden_ability                  1083 non-null   object
 25  is_mythical                     1459 non-null   bool
 26  is_legendary                    1459 non-null   bool
 27  is_sublegendary                 1459 non-null   bool
 28  is_powerhouse                   1459 non-null   bool
 29  is_regional                     1459 non-null   bool
 30  has_mega                        1459 non-null   bool
 31  has_gmax                        1459 non-null   bool
 32  sprite_default                  1459 non-null   object
dtypes: bool(7), int64(16), object(10)
memory usage: 317.7+ KB

In [25]:
#df_full.loc[[493]]

---

# CAPA GOLD

In [47]:
# pokemon
gold_pokemon = (
    df_merge
    .loc[:,
        [
            'id',
            'pokemon_name',
            'pokemon_base_name', 
            'species_id', 
            'species_name_en', 
            'height', 'weight', 
            'base_experience', 
            'is_default', 
            'is_separated_from_species', 
            'has_gender_differences', 
            #'forms_list', 
            'pokemon_first_type', 'pokemon_second_type', 
            'stat_hp_base', 'stat_attack_base', 'stat_defense_base', 
            'stat_special_attack_base', 'stat_special_defense_base', 'stat_speed_base', 
            'stat_hp_effort', 'stat_attack_effort', 'stat_defense_effort',
            'stat_special_attack_effort', 'stat_special_defense_effort', 'stat_speed_effort',
            'stats_total', 'effort_total', 
            'first_ability', 'second_ability', 'hidden_ability', 
            'is_mega', 'is_gmax', 'is_totem', 'is_regional',
            'evolves_from_pokemon_base_name',
            'evolutions',
            'is_mythical', 'is_legendary', 'is_sublegendary', 'is_powerhouse', 
            'has_mega', 'has_gmax', 
            'sprite_default',
        ]
    ]
)

# save
gold_pokemon.to_parquet(f'./{gold}/pokemon.parquet')

In [ ]:
# pokemon species
gold_species = (
    df_species_clean
    .loc[:,
        [
            'species_id',
            'species_name',
            'species_name_en',
            'genus',
            'base_happiness', 'capture_rate', 'forms_switchable', 
            'gender_rate', 'has_gender_differences', 'hatch_counter',
            'color_name', 'growth_rate_name', 'habitat_name', 'shape_name',
            'first_egg_group', 'second_egg_group', 
            'evolves_from_species_name', 
            'is_baby', 
            'is_legendary', 'is_mythical', 'is_sublegendary', 'is_powerhouse',
            'species_generation_number',
            'varieties_list', 
            'forms_description', 
            'has_mega', 'has_gmax', 'has_regional', 
            
            'red_en', 'blue_en', 'yellow_en', 'gold_en', 'silver_en', 'crystal_en', 'ruby_en',
            'sapphire_en', 'emerald_en', 'firered_en', 'leafgreen_en', 'diamond_en',
            'pearl_en', 'platinum_en', 'heartgold_en', 'soulsilver_en', 'black_en',
            'white_en', 'black_2_en', 'white_2_en', 'x_en', 'y_en', 'omega_ruby_en',
            'alpha_sapphire_en', 'sun_en', 'moon_en', 'ultra_sun_en',
            'ultra_moon_en', 'lets_go_pikachu_en', 'lets_go_eevee_en', 'sword_en',
            'shield_en', 'legends_arceus_en', 'scarlet_en', 'violet_en'
        ]
    ]
)

# save
gold_species.to_parquet(f'./{gold}/pokemon-species.parquet')

In [49]:
# pokemon forms
gold_forms = (
    df_full
    .loc[:,
        [
            'species_id',
            'species_name_en',
            'form_name_text', 
            'form_generation_number', 'version_group_name', 
            'species_name',
            'pokemon_name', 'pokemon_base_name', 
            'pokemon_form_name', 'pokemon_form_name_text', 
            'first_type', 'second_type',
            'first_ability', 'second_ability', 'hidden_ability',
            'height', 'weight', 'base_experience',
            'stat_hp_base', 'stat_attack_base', 'stat_defense_base',
            'stat_special_attack_base', 'stat_special_defense_base',
            'stat_speed_base', 'stat_hp_effort', 'stat_attack_effort',
            'stat_defense_effort', 'stat_special_attack_effort',
            'stat_special_defense_effort', 'stat_speed_effort', 
            'stats_total', 'effort_total', 
            'evolves_from_pokemon_base_name', 'evolutions',
            'is_default', 'is_mega', 'is_gmax', 'is_regional', 
            'is_totem', 'is_separated_from_species',
            'has_gender_differences', 'is_battle_only', 
            'is_legendary', 'is_sublegendary', 'is_mythical', 'is_powerhouse', 
            'has_mega', 'has_gmax',
            'sprite_default'
        ]
    ]
)

# save
gold_forms.to_parquet(f'./{gold}/pokemon-forms.parquet')

In [ ]:
# test

In [ ]:
#gold_list = pd.read_parquet('./streamlit/data/pokemon-forms.parquet')

In [ ]:
# (df_merge.is_default) | (df_merge.is_mega) | (df_merge.is_gmax) | (df_merge.is_regional & ~df_merge.is_totem) | (df_merge.pokemon_name=='eternatus-eternamax')